config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items do
    member do
      patch :complete
    end
  end

  
end

app/models/item.rb
class Item < ActiveRecord::Base
  def completed?
      !completed_at.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @items = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
  else
    render 'edit'
  end
end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  private

  def item_params
      params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Aufgabe editieren</h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Aufgabe" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit, "Editieren" %>
<% end %>

app/views/items/index.html.erb
<h1>Meine Aufgaben</h1>
<%= link_to "Neuer Eintrag", new_item_path, class: "btn btn-default"%>
<hr>

<% @items.each do |item| %>
    <div class="row item">
        <% if item.completed? %>
              <div class="col-md-6">
                <h2><s><%= link_to item.title, item %></s></h2>
                <p><%= time_ago_in_words(item.completed_at)%> ago.</p>
               </div>
              <div class="col-md-2">
          </div>
      <% else %>
            <div class="col-md-6">
              <h2><%= link_to item.title, item %></h2>
              <p><%= item.description %></p>
            </div>
            <div class="col-md-2">
              <%= link_to complete_item_path(item), method: :patch do %>
                <h2><i class="fa fa-flag-checkered" aria-hidden="true"></i></h2>
      <% end %>
          </div>
  <% end %>


  </div>
  <% end %>

app/views/items/new.html.erb
<h1>Neuen Eintrag vornehmen</h1>

<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Aufgabe" %>
  <%= f.input :description, label: "Beschreibung" %>
  <%= f.button :submit, "Erstellen" %>
<% end %>

app/views/items/show.html.erb
<h2><%= @item.title %></h2>
<p><%= @item.description %></p>
<hr>

<%= link_to root_path, class: "btn btn-default" do %>
  <i class="fa fa-chevron-left" aria-hidden="true"><h6>Zurück</h6></i>
<% end %>
<%= link_to edit_item_path, class: "btn btn-default" do %>
  <i class="fa fa-pencil-square-o" aria-hidden="true"><h6>Editieren</h6></i>
<% end %>
<%= link_to item_path(@item), method: :delete, data: { confirm: "Bist du sicher?"}, class: "btn btn-default" do %>
  <i class="fa fa-trash" aria-hidden="true"><h6>Löchen</h6></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datenproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>